alias: finance
author: TEam Swift
link: https://ng-erp.com
document: http://ones_manual.mydoc.io/?t=35708
requirements:

auth_nodes:

include:
    js:
        - apps/finance/main
        - apps/finance/model